In [2]:
#importing needed libraries
import numpy as np
import pandas as pd
import json
from fancyimpute import KNN

Using TensorFlow backend.


In [ ]:
test_range = range(2009, 2019)
file_list = []
for x in test_range:
    file_front = 'BRFSS_'
    file_back = '{}.csv'.format(x)
    file_list.append(file_front + file_back) 

In [4]:
impute_BRFSS = pd.read_csv('impute_BRFSS')
impute_BRFSS.shape

(4561861, 29)

In [5]:
# Removing countries outside of the continuous United States to declutter
impute_BRFSS = impute_BRFSS[impute_BRFSS['_STATE'] < 66]
impute_BRFSS.to_csv('impute_BRFSS', index=None)

In [8]:
impute_BRFSS.isnull().sum()

_STATE            0
GENHLTH     2243204
PHYSHLTH         53
MENTHLTH         41
POORHLTH    2185976
PERSDOC2        905
MEDCOST         906
CHECKUP1        905
MARITAL        2398
CHILDREN       5330
EDUCA          3601
INCOME2       22371
SEX          430949
PAINACT2    4529199
QLMENTL2    4529230
QLSTRES2    4529254
QLHLTH2     4529296
MISTMNT     4350183
HLTHPLN1     869544
ADDEPEV2     870687
INTERNET    2290613
DECIDE      1908926
DIFFALON    1918439
MEDICARE    3813777
NOCOV121    3818557
LSTCOVRG    4484653
DRVISITS    3741282
CARERCVD    3741318
RENTHOM1    2328094
dtype: int64

In [7]:
imputer = KNN()
imputed_BRFSS = pd.DataFrame(np.round(imputer.fit_transform(impute_BRFSS)), columns = impute_BRFSS.columns)

MemoryError: 

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In [81]:
for x in range(2009, 2019):
    holder = Mega_BRFSS.at[x, 'File']
     
    for column in holder.columns:
        for spot in final_round:
            if spot == column:
                print(column, '\n',Questions[Questions.variablename ==spot].responses.unique(), '\n', holder[column].unique(), '\n')
                if 99 in holder[column].unique():
                    Mega_BRFSS.at[x, 'File'][column].fillna(99, inplace=True)
                    print('After fix:', column, '\n', Mega_BRFSS.at[x, 'File'][column].unique(), '\n')
                elif 9 in holder[column].unique():
                    Mega_BRFSS.at[x, 'File'][column].fillna(9, inplace=True)
                    print(column, '\n', Mega_BRFSS.at[x, 'File'][column].unique(), '\n')
                else:
                    pass

_STATE 
 [] 
 [ 1.  2.  4.  5.  6.  8.  9. 10. 11. 12. 13. 15. 16. 17. 18. 19. 20. 21.
 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39.
 40. 41. 42. 44. 45. 46. 47. 48. 49. 50. 51. 53. 54. 55. 56. 66. 72. 78.] 

_STATE 
 [ 1.  2.  4.  5.  6.  8.  9. 10. 11. 12. 13. 15. 16. 17. 18. 19. 20. 21.
 22. 23. 24. 25. 26. 27. 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39.
 40. 41. 42. 44. 45. 46. 47. 48. 49. 50. 51. 53. 54. 55. 56. 66. 72. 78.] 

GENHLTH 
 ['1=Excellent  2=Very good  3=Good  4=Fair  5=Poor  7=DK/NS  9=Refused'] 
 [3. 4. 5. 2. 1. 7. 9.] 

GENHLTH 
 [3. 4. 5. 2. 1. 7. 9.] 

PHYSHLTH 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refused'] 
 [88. 15.  7. 30.  4. 77.  2.  1.  3. 10. 23. 21. 20. 14.  5. 12.  8.  6.
 22. 25. 29. 11. 18. 99. 27. 28.  9. 24. 16. 17. 13. 19. 26.] 

After fix: PHYSHLTH 
 [88. 15.  7. 30.  4. 77.  2.  1.  3. 10. 23. 21. 20. 14.  5. 12.  8.  6.
 22. 25. 29. 11. 18. 99. 27. 28.  9. 24. 16. 17. 13. 19. 26.] 

MENTHLTH 
 ['

PHYSHLTH 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refused'] 
 [88. 12. 25. 30.  1. 10. 28. 20. 14.  5.  2. 77. 99. 15.  7.  3.  4.  6.
 11. 21.  8.  9. 16. 27. 23. 29. 18. 26. 13. 22. 17. 24. 19.] 

After fix: PHYSHLTH 
 [88. 12. 25. 30.  1. 10. 28. 20. 14.  5.  2. 77. 99. 15.  7.  3.  4.  6.
 11. 21.  8.  9. 16. 27. 23. 29. 18. 26. 13. 22. 17. 24. 19.] 

MENTHLTH 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refused'] 
 [30.  4.  3. 88. 15.  2.  5. 14. 10. 99.  7. 28. 20. 25.  1. 26.  6. 77.
 12.  9. 29. 18. 21.  8. 27. 16. 17. 24. 22. 23. 11. 13. 19.] 

After fix: MENTHLTH 
 [30.  4.  3. 88. 15.  2.  5. 14. 10. 99.  7. 28. 20. 25.  1. 26.  6. 77.
 12.  9. 29. 18. 21.  8. 27. 16. 17. 24. 22. 23. 11. 13. 19.] 

POORHLTH 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refused'] 
 [88.  4. 99. 25. 30.  3. 15.  7. 14. 20.  1. 12. 10.  2.  5. 77.  6. 21.
  8. 16. 28. 18. 27. 13. 23. 26.  9. 24. 29. 22. 17. 19. 11.] 

After fix: POORHLTH 
 [88.  4. 99.

After fix: POORHLTH 
 [30. 99. 88. 10.  5.  4. 77. 14. 20.  3.  2. 15.  1.  7. 28.  6. 25. 26.
 13.  9. 12. 21. 29.  8. 16. 22. 18. 17. 27. 23. 24. 19. 11.] 

HLTHPLN1 
 ['1=Yes 2=No 7=Don’t know/Not Sure 9=Refused'] 
 [1. 2. 7. 9.] 

HLTHPLN1 
 [1. 2. 7. 9.] 

PERSDOC2 
 ['1=Yes, only one 2=More than one 3=No 7=Don’t know/Not Sure 9=Refused'] 
 [1. 2. 3. 7. 9.] 

PERSDOC2 
 [1. 2. 3. 7. 9.] 

MEDCOST 
 ['1=Yes 2=No 7=Don’t know/Not sure 9=Refused'] 
 [2. 1. 9. 7.] 

MEDCOST 
 [2. 1. 9. 7.] 

CHECKUP1 
 ['1=Within past year (anytime less than 12 months ago) 2=Within past 2 years (1 year but less than 2 years ago) 3=Within past 5 years (2 years but less than 5 years ago) 4=5 or more years ago 7=Don’t know/Not sure 8=Never 9=Refused'] 
 [1. 2. 4. 3. 7. 9. 8.] 

CHECKUP1 
 [1. 2. 4. 3. 7. 9. 8.] 

ADDEPEV2 
 ['1=Yes 2=No 7=Don’t know/Not sure 9=Refused'] 
 [1. 2. 7. 9.] 

ADDEPEV2 
 [1. 2. 7. 9.] 

MARITAL 
 ['1=Married 2=Divorced 3=Widowed 4=Separated 5=Never married 6=A member of an unm

DECIDE 
 ['1=Yes 2=No 7=Don’t know/Not Sure 9=Refused'] 
 [2. 1. 7. 9.] 

DECIDE 
 [2. 1. 7. 9.] 

DIFFALON 
 ['1=Yes 2=No 7=Don’t know/Not Sure 9=Refused'] 
 [2. 1. 7. 9.] 

DIFFALON 
 [2. 1. 7. 9.] 

PAINACT2 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refused'] 
 [99. 88.  7. 25. 30. 15.  5. 77. 28.  3.  4.  1. 10. 20.  8.  2. 14.  6.
 16. 12. 29. 11.  9. 26. 24. 23. 18. 22. 21. 27. 17. 19.] 

After fix: PAINACT2 
 [99. 88.  7. 25. 30. 15.  5. 77. 28.  3.  4.  1. 10. 20.  8.  2. 14.  6.
 16. 12. 29. 11.  9. 26. 24. 23. 18. 22. 21. 27. 17. 19.] 

QLMENTL2 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refused'] 
 [99. 88. 77.  2. 25. 10.  4. 30.  7.  1. 15. 28.  3. 20.  5.  8.  6. 12.
  9. 27. 14. 23. 22. 29. 18. 16. 21. 17. 13. 26. 11.] 

After fix: QLMENTL2 
 [99. 88. 77.  2. 25. 10.  4. 30.  7.  1. 15. 28.  3. 20.  5.  8.  6. 12.
  9. 27. 14. 23. 22. 29. 18. 16. 21. 17. 13. 26. 11.] 

QLSTRES2 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refus

After fix: MENTHLTH 
 [88.  1.  3.  5. 30.  2. 10. 26. 15. 25.  4. 20. 77. 99.  7. 14. 12.  8.
 29.  9. 13.  6. 16. 22. 21. 28. 18. 23. 17. 11. 27. 24. 19.] 

POORHLTH 
 ['1-30=Number of days 88=None 77=Don’t know/Not sure 99=Refused'] 
 [99. 88.  3. 28.  1.  4.  2.  5. 30.  8. 25.  7. 15. 14. 77. 20. 10. 17.
 12.  6. 29. 21. 26. 11.  9. 19. 23. 13. 22. 18. 16. 27. 24.] 

After fix: POORHLTH 
 [99. 88.  3. 28.  1.  4.  2.  5. 30.  8. 25.  7. 15. 14. 77. 20. 10. 17.
 12.  6. 29. 21. 26. 11.  9. 19. 23. 13. 22. 18. 16. 27. 24.] 

HLTHPLN1 
 ['1=Yes 2=No 7=Don’t know/Not Sure 9=Refused'] 
 [1. 2. 9. 7.] 

HLTHPLN1 
 [1. 2. 9. 7.] 

PERSDOC2 
 ['1=Yes, only one 2=More than one 3=No 7=Don’t know/Not Sure 9=Refused'] 
 [2. 1. 3. 9. 7.] 

PERSDOC2 
 [2. 1. 3. 9. 7.] 

MEDCOST 
 ['1=Yes 2=No 7=Don’t know/Not sure 9=Refused'] 
 [2. 1. 7. 9.] 

MEDCOST 
 [2. 1. 7. 9.] 

CHECKUP1 
 ['1=Within past year (anytime less than 12 months ago) 2=Within past 2 years (1 year but less than 2 years ago) 3=Wi

RENTHOM1 
 ['1=Own 2=Rent 3=Other arrangement 7=Don’t know/Not Sure 9=Refused'] 
 [1. 2. 3. 9. 7.] 

RENTHOM1 
 [1. 2. 3. 9. 7.] 

CHILDREN 
 ['1-87=Number of children 88=None 99=Refused'] 
 [88.  1.  3.  2.  4. 99.  5.  6.  8. 10.  9.  7. 17. 12. 13. 11. 15. 72.
 14. 16. 23.] 

After fix: CHILDREN 
 [88.  1.  3.  2.  4. 99.  5.  6.  8. 10.  9.  7. 17. 12. 13. 11. 15. 72.
 14. 16. 23.] 

INCOME2 
 ['1=Less than $10,000 2=Less than $15,000 ($10,000 to less than $15,000) 3=Less than $20,000 ($15,000 to less than $20,000) 4=Less than $25,000 ($20,000 to less than $25,000) 5=Less than $35,000 ($25,000 to less than $35,000) 6=Less than $50,000 ($35,000 to less than $50,000) 7=Less than $75,000 ($50,000 to less than $75,000) 8=$75,000 or more 77=Don’t know/Not sure 99=Refused'] 
 [ 6.  8. 99.  1.  2.  4.  5. 77.  7.  3.] 

After fix: INCOME2 
 [ 6.  8. 99.  1.  2.  4.  5. 77.  7.  3.] 

INTERNET 
 ['1=Yes 2=No 7=Don’t know/Not Sure 9=Refused'] 
 [1. 2. 9. 7.] 

INTERNET 
 [1. 2. 9. 7.] 

DEC

In [82]:
for x in range(2009, 2019):
    holder = Mega_BRFSS.at[x, 'File']
    percent_missing = holder.isnull().sum()*100/len(holder)
    print('\n', x, '\n',percent_missing)


 2009 
 _STATE        0.0
GENHLTH       0.0
PHYSHLTH      0.0
MENTHLTH      0.0
POORHLTH      0.0
PERSDOC2      0.0
MEDCOST       0.0
CHECKUP1      0.0
MARITAL       0.0
CHILDREN      0.0
EDUCA         0.0
INCOME2       0.0
SEX           0.0
PAINACT2    100.0
QLMENTL2    100.0
QLSTRES2    100.0
QLHLTH2     100.0
MISTMNT       0.0
dtype: float64

 2010 
 _STATE      0.0
GENHLTH     0.0
PHYSHLTH    0.0
MENTHLTH    0.0
POORHLTH    0.0
PERSDOC2    0.0
MEDCOST     0.0
CHECKUP1    0.0
MARITAL     0.0
CHILDREN    0.0
EDUCA       0.0
INCOME2     0.0
SEX         0.0
PAINACT2    0.0
QLMENTL2    0.0
QLSTRES2    0.0
QLHLTH2     0.0
dtype: float64

 2011 
 _STATE        0.0
GENHLTH       0.0
PHYSHLTH      0.0
MENTHLTH      0.0
POORHLTH      0.0
HLTHPLN1      0.0
PERSDOC2      0.0
MEDCOST       0.0
CHECKUP1      0.0
ADDEPEV2      0.0
MARITAL       0.0
CHILDREN      0.0
EDUCA         0.0
INCOME2       0.0
SEX           0.0
PAINACT2    100.0
QLMENTL2    100.0
QLSTRES2    100.0
QLHLTH2     100.0
MISTM

In [151]:
BRFSS_FINAL = pd.concat(files)

In [152]:
for column in BRFSS_FINAL:
    if 99. in BRFSS_FINAL[column].unique():
        BRFSS_FINAL[column].fillna(99., inplace=True)
    else:
        BRFSS_FINAL[column].fillna(9., inplace=True)

In [156]:
BRFSS_FINAL.to_csv('BRFSS_FINAL', index=None)
Questions.to_csv('Questions', index=None)